### PR TITLE
OSS process compliance stuff

### PR DESCRIPTION
**Pull request by freeformz**
Connects to heroku/opex-team#243

- [ ]  License headers in each source file
- [ ] Code and Documentation Quality

### CODE REVIEW

**Comment by freeformz** [comment]
@schneems I have no idea what code climate is doing or why it's failing.

**Review by amerine — COMMENTED** [review]
LGTM, but I'm not a lawyer. :-/

**Comment by schneems** [comment]
You're missing a few trailing newlines. Does the notice really have to go in every file? I would have thought since it's shipped as a package it would have just needed to be included in the package.

**Comment by freeformz** [comment]
@schneems Sorry about the trailing newlines. According to the current OSS process, yes, every file needs the header. Since the MIT license is small, I just included it instead of figuring out what qualifies as the header.

**Pull request merged**
